name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  check:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict


  build-test-coverage:

    runs-on: macos-12

    needs: [check]

    strategy:
      matrix:
        platform: [macos, ios, watchos, tvos]
        xcode: ["14.2"]

    steps:
      
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    - name: Select Swift
      uses: swift-actions/setup-swift@v1

    - name: Build/Test
      run: make build-test-${{ matrix.platform }}

    - name: Test Coverage
      uses: maxep/spm-lcov-action@0.3.0
      if: ${{ matrix.platform == 'macos' && matrix.xcode == '12.5.1' }}
      with:
        output-file: ./coverage/lcov.info

    - name: Report Coverage
      uses: romeovs/lcov-reporter-action@v0.2.21
      if: ${{ matrix.platform == 'macos' && matrix.xcode == '12.5.1' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

    - name: Updload Reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: reports
        path: TestResults
